version: '3.7'

services:
  api-itmo:
    build:
      context: src
      dockerfile: Dockerfile
    image: api_itmo
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/src
    working_dir: /src
    command: gunicorn -c configs/gunicorn.conf.py start:app
